global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go-services'
    static_configs:
      - targets: ['api-gateway:8080', 'chat-gateway:8082', 'llm-gateway-py:50054', 'avatar-service:8090', 'notification:8084']

  - job_name: 'java-services'
    static_configs:
      - targets: ['auth-core:8081', 'rec-service:8083']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200'] 