// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: llm/v1/llm.proto

package llmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LLMService_GenerateStream_FullMethodName = "/llm.v1.LLMService/GenerateStream"
)

// LLMServiceClient is the client API for LLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMServiceClient interface {
	// GenerateStream streams responses from the LLM.
	GenerateStream(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (LLMService_GenerateStreamClient, error)
}

type lLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &lLMServiceClient{cc}
}

func (c *lLMServiceClient) GenerateStream(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (LLMService_GenerateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &LLMService_ServiceDesc.Streams[0], LLMService_GenerateStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &lLMServiceGenerateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LLMService_GenerateStreamClient interface {
	Recv() (*GenerateResponse, error)
	grpc.ClientStream
}

type lLMServiceGenerateStreamClient struct {
	grpc.ClientStream
}

func (x *lLMServiceGenerateStreamClient) Recv() (*GenerateResponse, error) {
	m := new(GenerateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LLMServiceServer is the server API for LLMService service.
// All implementations must embed UnimplementedLLMServiceServer
// for forward compatibility
type LLMServiceServer interface {
	// GenerateStream streams responses from the LLM.
	GenerateStream(*GenerateRequest, LLMService_GenerateStreamServer) error
	mustEmbedUnimplementedLLMServiceServer()
}

// UnimplementedLLMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLLMServiceServer struct {
}

func (UnimplementedLLMServiceServer) GenerateStream(*GenerateRequest, LLMService_GenerateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GenerateStream not implemented")
}
func (UnimplementedLLMServiceServer) mustEmbedUnimplementedLLMServiceServer() {}

// UnsafeLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServiceServer will
// result in compilation errors.
type UnsafeLLMServiceServer interface {
	mustEmbedUnimplementedLLMServiceServer()
}

func RegisterLLMServiceServer(s grpc.ServiceRegistrar, srv LLMServiceServer) {
	s.RegisterService(&LLMService_ServiceDesc, srv)
}

func _LLMService_GenerateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LLMServiceServer).GenerateStream(m, &lLMServiceGenerateStreamServer{stream})
}

type LLMService_GenerateStreamServer interface {
	Send(*GenerateResponse) error
	grpc.ServerStream
}

type lLMServiceGenerateStreamServer struct {
	grpc.ServerStream
}

func (x *lLMServiceGenerateStreamServer) Send(m *GenerateResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LLMService_ServiceDesc is the grpc.ServiceDesc for LLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.v1.LLMService",
	HandlerType: (*LLMServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateStream",
			Handler:       _LLMService_GenerateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "llm/v1/llm.proto",
}
