server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 120s

auth:
  service_addr: "auth-core:9091"
  jwt_secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  access_token_ttl: 15m
  refresh_token_ttl: 168h

chat:
  service_addr: "chat-gateway:8082"

ilo:
  service_addr: "auth-core:9091"

llm:
  service_addr: "llm-gateway:50053"

rate_limit:
  enabled: true
  requests_per_minute: 100
  redis_addr: "redis:6379"

tracing:
  enabled: true
  service_name: "api-gateway"
  endpoint: "tempo:4317"
  insecure: true