-- Migration script to import all 60 ILO questions into ilo_questions table
-- Only question_number and question_text are included for simplicity

INSERT INTO ilo_questions (question_number, question_text) VALUES
(1, 'Sử dụng từ ngữ để diễn tả suy nghĩ, quan sát và trải nghiệm của bạn thành văn viết cho người khác đọc. Diễn tả ý tưởng, tin tức, hiểu biết, số liệu dưới dạng viết.'),
(2, 'Học và sử dụng các ngôn ngữ mới (nghe, nói, đọc, viết).'),
(3, 'Đọc sách, văn bản, bài luận, bài báo để hiểu nội dung. Kiểm tra và/ hoặc soạn các tài liệu như di chúc, văn bằng chứng chỉ, giấy phép, báo cáo kế toán.'),
(4, 'Thông qua ngôn từ rõ ràng, mạch lạc để truyển tải đến người khác các kiến thức, các nội dung họ chưa biết, khiến họ hiểu được qua những chỉ dẫn, thuyết trình của mình.'),
(5, 'Thảo luận các vấn đề, đưa ra câu, từ rõ nghĩa, nói lưu loát, để bảo vệ ý kiến của mình...'),
(6, 'Kiểm tra nghĩa của từ, dịch từ ngôn ngữ này sang ngôn ngữ khác, sử dụng từ mới để truyền đạt ý tưởng một cách rõ ràng, tìm những từ phù hợp nhất cho một ý tưởng.'),
(7, 'Kiểm tra xem câu từ, ngữ pháp và chính tả có chính xác, đúng văn phạm tiếng Việt không.'),
(8, 'Viết ý tưởng, suy nghĩ và trải nghiệm của bạn thành lời để mọi người thích đọc những gì bạn viết. Bài viết có thể dưới dạng bài văn, bài báo, truyện, thơ, báo cáo.'),
(9, 'Dùng lời nói để trình bày ý tưởng với mọi người. Giảng dạy, thuyết trình, làm mẫu hoặc diễn thuyết.'),
(10, 'Nói chuyện hấp dẫn để mọi người thích nghe bạn nói. Sử dụng ngôn ngữ chính xác. Nói rõ ràng.'),
(11, 'Đọc và hiểu những gì mọi người viết ra. Phát hiện ra sai sót trong văn bản viết.'),
(12, 'Hiểu ý nghĩa những gì người khác nói. Có thể tập trung và không bỏ sót chi tiết nào.'),
(13, 'Tìm hiểu tại sao một công việc kinh doanh tại thành thị hay nông thôn không thuận lợi và nghĩ phương án để cải thiện. Thử các biện pháp để tìm ra cách làm ăn phát đạt hơn. So sánh các loại hình kinh doanh khác nhau để hiểu cách hoạt động kinh doanh.'),
(14, 'Nghiên cứu kĩ thông tin ở các dạng khác nhau và hiểu sâu ý nghĩa của thông tin. Áp dụng toán học và thống kê. Phát hiện điểm đặc biệt của thông tin để tìm ra xu hướng.'),
(15, 'Dự báo những gì có thể xảy ra dựa trên tính toán các dữ liệu thông tin bạn có và đề xuất kế hoạch tương lai.'),
(16, 'Sử dụng con số, tìm kiếm bằng chứng, kiểm tra phép tính.'),
(17, 'Sắp xếp thông tin theo trình tự để người khác có thể dễ dàng hiểu và sử dụng.'),
(18, 'Giải ô chữ, giải quyết các vấn đề thuộc nhiều lĩnh vực bằng cách sử dụng kiến thức và thông tin chính xác.'),
(19, 'Áp dụng các nguyên tắc trong các môn như toán học, thống kê, vật lí, hóa học để tìm hiểu và giải quyết vấn đề.'),
(20, 'Hiểu những gì đang diễn ra để quyết định hành động tiếp theo. Suy nghĩ nhanh.'),
(21, 'Xác định vấn đề, xây dựng các phương pháp nghiên cứu, thu thập và phân tích thông tin để hiểu rõ hoặc giải quyết vấn đề.'),
(22, 'Áp dụng các nguyên tắc số học và đại số để tìm hiểu vấn đề hoặc thực hiện nhiệm vụ.'),
(23, 'Làm việc với con số, áp dụng số học và đại số.'),
(24, 'Cộng, trừ, nhân, chia, áp dụng công thức để có kết quả chính xác.'),
(25, 'Tự suy nghĩ, sáng tạo để làm ra đồ vật mới.'),
(26, 'Tạo ra bản sao của các vật thông qua quan sát và tưởng tượng.'),
(27, 'Sắp đặt các vật thể cho đẹp, tạo ra sản phẩm từ các chất liệu khác nhau (như gỗ, vải, đất sét…) để cho đẹp mắt hoặc để sử dụng được.'),
(28, 'Vẽ bằng các vật liệu khác nhau như sơn, bút chì, than hoặc vật liệu bất kì bằng cách sao chép, quan sát và tưởng tượng.'),
(29, 'Phối hợp màu sắc, trang trí bằng màu để đồ vật trông đẹp mắt.'),
(30, 'Diễn đạt ý tưởng, suy nghĩ và trải nghiệm của bạn thành hình ảnh để mọi người thích xem/ sử dụng sản phẩm bạn tạo ra. Có thể dưới dạng tranh vẽ, tượng và điêu khắc, thêu thùa, sơn mài hoặc những sản phẩm tương tự.'),
(31, 'Tạo ra các sản phẩm dùng hàng ngày từ trí tưởng tượng của bạn. Đó có thể là quần áo, vật dụng, đồ trang sức, giày dép, gốm sứ hoặc các vật tương tự.'),
(32, 'Tạo ra các sản phẩm từ trí tưởng tượng của bạn. Đó có thể là công trình kiến trúc, cầu, đường, ô tô, thiết kế cảnh quan và các sản phẩm cần thiết cho tiện nghi đời sống.'),
(33, 'Sử dụng các công cụ, vật liệu khác nhau như: cọ vẽ, bút chì, khuôn, màu vẽ, đất nặn, giấy màu,… để vẽ và tạo ra các sản phẩm có tính nghệ thuật.'),
(34, 'Áp dụng các định lí hình học để xây dựng, sáng tạo và gia cố các sản phẩm. Tính toán diện tích, thể tích,... Làm việc với các hình khối khác nhau.'),
(35, 'Uốn, gấp, ghép, đính và nối các vật liệu để tạo ra sản phẩm.'),
(36, 'Trang trí lại đồ vật cho đẹp mắt hơn. Sử dụng các kĩ thuật, mĩ phẩm, quần áo, trang sức khác nhau để làm đẹp cho mọi người, đồ vật.'),
(37, 'Lãnh đạo nhóm bằng cách đề ra phương thức làm việc cùng nhau, cùng nhau giải quyết vấn đề, cùng làm việc theo nhóm đẻ thực hiện mục tiêu.'),
(38, 'Tìm hiểu cách hoạt động kinh doanh. Tìm hiểu những con người trong đó và cách hành xử của họ. Giúp mọi người hoàn thành tốt trách nhiệm của họ trong kinh doanh'),
(39, 'Lên kế hoạch tổ chức hội họp và hoạt động, sắp xếp các buổi gặp gỡ, quản lí các sự kiện.'),
(40, 'Tìm hiểu các bộ phận của một tổ chức và nhiệm vụ của mọi người. Giúp họ làm việc cùng nhau một cách hiệu quả.'),
(41, 'Tìm hiểu một nhóm cụ thể hoạt động như thế nào. Tìm hiểu xem những người khác nhau trong nhóm ảnh hưởng lẫn nhau như thế nào.'),
(42, 'Hiểu mối quan hệ giữa người và người. Sử dụng các phương pháp tâm lí khác nhau để giúp mọi người quan hệ với nhau theo cách tích cực.'),
(43, 'Giúp mọi người hiểu được nguyện vọng và mục đích của họ. Giúp họ nhận ra các cơ hội khác nhau. Giúp họ chọn con đường tốt nhất để đạt được mục đích.'),
(44, 'Hiểu tại sao mọi người tiến hành công việc theo cách họ đang làm. Tìm hiểu cảm giác của mọi người và ảnh hưởng của tâm trạng tới hành động của họ.'),
(45, 'Giành được lòng tin của mọi người. Áp dụng kiến thức y tế để làm giảm nỗi đau và sự chịu đựng về mặt thể chất.Hỗ trợ khi họ yếu đuối về mặt thể chất. Luôn có mặt mỗi khi họ cần sự quan tâm giúp đỡ.'),
(46, 'Giành được lòng tin của mọi người. Áp dụng kiến thức tâm lí để tìm hiểu lí do tại sao họ lại buồn phiền. Nhạy cảm với tâm trạng và cảm xúc của mọi người. Áp dụng các nguyên tắc tư vấn để giúp họ giải quyết các vấn đề tâm lí.'),
(47, 'Trình bày ý tưởng sao cho mọi người đồng tình với bạn, có thể là để bán một đồ vật. Thuyết phục mọi người đồng ý với một ý tưởng và có hành động.'),
(48, 'Tham dự các buổi gặp mặt đông người. Làm quen với người lạ. Trò chuyện với những người bạn không biết nhiều.'),
(49, 'Làm việc tại nơi có nhiều máy móc, dụng cụ và hoạt động sản xuất.'),
(50, 'Làm việc với máy móc, sử dụng các công cụ để bảo đảm máy chạy tốt. Tìm nguyên nhân làm hỏng máy để phòng tránh.'),
(51, 'Làm việc ngoài trời tại những nơi như đồng ruộng, công trình xây dựng, rừng, sân chơi.'),
(52, 'Tìm hiểu về máy móc một cách khoa học. Áp dụng các định luật vật lí liên quan đến đòn bẩy, chuyển động quay, nhiệt, nhiệt độ, ma sát… để hiểu về máy móc một cách khoa học.'),
(53, 'Sử dụng vận động cơ thể để đạt được mục tiêu. Phối hợp tay và mắt nhuần nhuyễn. Các hoạt động như thể thao hay khiêu vũ chuyên nghiệp đòi hỏi phải sử dụng tất cả các bộ phận cơ thể một cách hợp lí.'),
(54, 'Sử dụng vận động cơ thể để đạt được mục tiêu. Làm các công việc đòi hỏi sức mạnh. Các hoạt động như thể thao chuyên nghiệp đòi hỏi bạn phải tiêu tốn năng lượng trong một khoảng thời gian dài mà không mệt mỏi.'),
(55, 'Sửa máy móc không hoạt động được và làm nó hoạt động trở lại bằng cách vệ sinh, thay thế phụ tùng, lắp lại bộ phận hoặc thêm bộ phận mới.'),
(56, 'Tham gia các hoạt động đòi hỏi nhiều về thể lực mà không mệt mỏi, ví dụ như làm việc đồng áng hoặc thể thao chuyên nghiệp.'),
(57, 'Sử dụng máy móc để thực hiện nhiệm vụ. Có thể là nâng, cắt, uốn, cuộn, ghép hay khoan các vật liệu như kim loại, vải, đá, đất hay chất liệu nhân tạo.'),
(58, 'Lặp đi lặp lại chuyển động của cơ thể trong thời gian ngắn nhất. Thực hiện một chuỗi hoạt động thể chất (ví dụ như kẹp - cắt - gập) với tốc độ nhanh mà không sai sót.'),
(59, 'Điểu khiển chuyển động tay để làm các nhiệm vụ đòi hỏi sự tinh xảo.'),
(60, 'Kéo căng và di chuyển cơ thể tới những vị trí khó mà không bị ngã. Các hoạt động như thể thao chuyên nghiệp và nhảy múa.');
