// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: careerup/v1/chat.proto

package careerupv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamRequest represents a single token in the conversation stream
type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Text           string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerup_v1_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_careerup_v1_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_careerup_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *StreamRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// StreamResponse represents a response from the LLM
type StreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*StreamResponse_Token
	//	*StreamResponse_AvatarUrl
	Response isStreamResponse_Response `protobuf_oneof:"response"`
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerup_v1_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_careerup_v1_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_careerup_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (m *StreamResponse) GetResponse() isStreamResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *StreamResponse) GetToken() string {
	if x, ok := x.GetResponse().(*StreamResponse_Token); ok {
		return x.Token
	}
	return ""
}

func (x *StreamResponse) GetAvatarUrl() string {
	if x, ok := x.GetResponse().(*StreamResponse_AvatarUrl); ok {
		return x.AvatarUrl
	}
	return ""
}

type isStreamResponse_Response interface {
	isStreamResponse_Response()
}

type StreamResponse_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type StreamResponse_AvatarUrl struct {
	AvatarUrl string `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3,oneof"`
}

func (*StreamResponse_Token) isStreamResponse_Response() {}

func (*StreamResponse_AvatarUrl) isStreamResponse_Response() {}

// WebSocketMessage represents the JSON structure for WebSocket communication
type WebSocketMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*WebSocketMessage_UserMessage
	//	*WebSocketMessage_AssistantToken
	//	*WebSocketMessage_AvatarUrl
	Payload isWebSocketMessage_Payload `protobuf_oneof:"payload"`
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerup_v1_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_careerup_v1_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_careerup_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *WebSocketMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (m *WebSocketMessage) GetPayload() isWebSocketMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *WebSocketMessage) GetUserMessage() *UserMessage {
	if x, ok := x.GetPayload().(*WebSocketMessage_UserMessage); ok {
		return x.UserMessage
	}
	return nil
}

func (x *WebSocketMessage) GetAssistantToken() *AssistantToken {
	if x, ok := x.GetPayload().(*WebSocketMessage_AssistantToken); ok {
		return x.AssistantToken
	}
	return nil
}

func (x *WebSocketMessage) GetAvatarUrl() *AvatarUrl {
	if x, ok := x.GetPayload().(*WebSocketMessage_AvatarUrl); ok {
		return x.AvatarUrl
	}
	return nil
}

type isWebSocketMessage_Payload interface {
	isWebSocketMessage_Payload()
}

type WebSocketMessage_UserMessage struct {
	UserMessage *UserMessage `protobuf:"bytes,2,opt,name=user_message,json=userMessage,proto3,oneof"`
}

type WebSocketMessage_AssistantToken struct {
	AssistantToken *AssistantToken `protobuf:"bytes,3,opt,name=assistant_token,json=assistantToken,proto3,oneof"`
}

type WebSocketMessage_AvatarUrl struct {
	AvatarUrl *AvatarUrl `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof"`
}

func (*WebSocketMessage_UserMessage) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_AssistantToken) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_AvatarUrl) isWebSocketMessage_Payload() {}

type UserMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConversationId string `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Text           string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerup_v1_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_careerup_v1_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_careerup_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *UserMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UserMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AssistantToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AssistantToken) Reset() {
	*x = AssistantToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerup_v1_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssistantToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantToken) ProtoMessage() {}

func (x *AssistantToken) ProtoReflect() protoreflect.Message {
	mi := &file_careerup_v1_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantToken.ProtoReflect.Descriptor instead.
func (*AssistantToken) Descriptor() ([]byte, []int) {
	return file_careerup_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *AssistantToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AvatarUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *AvatarUrl) Reset() {
	*x = AvatarUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_careerup_v1_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarUrl) ProtoMessage() {}

func (x *AvatarUrl) ProtoReflect() protoreflect.Message {
	mi := &file_careerup_v1_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarUrl.ProtoReflect.Descriptor instead.
func (*AvatarUrl) Descriptor() ([]byte, []int) {
	return file_careerup_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *AvatarUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_careerup_v1_chat_proto protoreflect.FileDescriptor

var file_careerup_v1_chat_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72,
	0x75, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x4c, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x22, 0x55, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a,
	0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xf1, 0x01, 0x0a, 0x10, 0x57,
	0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61, 0x72, 0x65,
	0x65, 0x72, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x61, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x61,
	0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x61, 0x73, 0x73, 0x69,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x37, 0x0a, 0x0a, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x48, 0x00, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x55, 0x72, 0x6c, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4a,
	0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x26, 0x0a, 0x0e, 0x41, 0x73,
	0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x1d, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x32, 0x5e, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x1a, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0xb1, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72,
	0x75, 0x70, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x43, 0x68, 0x61, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x2d, 0x49, 0x6e, 0x63, 0x2f, 0x63, 0x61, 0x72, 0x65,
	0x65, 0x72, 0x75, 0x70, 0x2d, 0x6d, 0x6f, 0x6e, 0x6f, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x2f, 0x76, 0x31, 0x3b,
	0x63, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58,
	0xaa, 0x02, 0x0b, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x0b, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x17, 0x43,
	0x61, 0x72, 0x65, 0x65, 0x72, 0x75, 0x70, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x43, 0x61, 0x72, 0x65, 0x65, 0x72, 0x75,
	0x70, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_careerup_v1_chat_proto_rawDescOnce sync.Once
	file_careerup_v1_chat_proto_rawDescData = file_careerup_v1_chat_proto_rawDesc
)

func file_careerup_v1_chat_proto_rawDescGZIP() []byte {
	file_careerup_v1_chat_proto_rawDescOnce.Do(func() {
		file_careerup_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_careerup_v1_chat_proto_rawDescData)
	})
	return file_careerup_v1_chat_proto_rawDescData
}

var file_careerup_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_careerup_v1_chat_proto_goTypes = []interface{}{
	(*StreamRequest)(nil),    // 0: careerup.v1.StreamRequest
	(*StreamResponse)(nil),   // 1: careerup.v1.StreamResponse
	(*WebSocketMessage)(nil), // 2: careerup.v1.WebSocketMessage
	(*UserMessage)(nil),      // 3: careerup.v1.UserMessage
	(*AssistantToken)(nil),   // 4: careerup.v1.AssistantToken
	(*AvatarUrl)(nil),        // 5: careerup.v1.AvatarUrl
}
var file_careerup_v1_chat_proto_depIdxs = []int32{
	3, // 0: careerup.v1.WebSocketMessage.user_message:type_name -> careerup.v1.UserMessage
	4, // 1: careerup.v1.WebSocketMessage.assistant_token:type_name -> careerup.v1.AssistantToken
	5, // 2: careerup.v1.WebSocketMessage.avatar_url:type_name -> careerup.v1.AvatarUrl
	0, // 3: careerup.v1.ConversationService.Stream:input_type -> careerup.v1.StreamRequest
	1, // 4: careerup.v1.ConversationService.Stream:output_type -> careerup.v1.StreamResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_careerup_v1_chat_proto_init() }
func file_careerup_v1_chat_proto_init() {
	if File_careerup_v1_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_careerup_v1_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerup_v1_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerup_v1_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebSocketMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerup_v1_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerup_v1_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssistantToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_careerup_v1_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_careerup_v1_chat_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*StreamResponse_Token)(nil),
		(*StreamResponse_AvatarUrl)(nil),
	}
	file_careerup_v1_chat_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*WebSocketMessage_UserMessage)(nil),
		(*WebSocketMessage_AssistantToken)(nil),
		(*WebSocketMessage_AvatarUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_careerup_v1_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_careerup_v1_chat_proto_goTypes,
		DependencyIndexes: file_careerup_v1_chat_proto_depIdxs,
		MessageInfos:      file_careerup_v1_chat_proto_msgTypes,
	}.Build()
	File_careerup_v1_chat_proto = out.File
	file_careerup_v1_chat_proto_rawDesc = nil
	file_careerup_v1_chat_proto_goTypes = nil
	file_careerup_v1_chat_proto_depIdxs = nil
}
