// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/chat.proto

package careerupv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenRequest represents a single token in the conversation stream
type TokenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *TokenRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// TokenResponse represents a response from the LLM
type TokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*TokenResponse_Token
	//	*TokenResponse_AvatarUrl
	Response      isTokenResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetResponse() isTokenResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		if x, ok := x.Response.(*TokenResponse_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *TokenResponse) GetAvatarUrl() string {
	if x != nil {
		if x, ok := x.Response.(*TokenResponse_AvatarUrl); ok {
			return x.AvatarUrl
		}
	}
	return ""
}

type isTokenResponse_Response interface {
	isTokenResponse_Response()
}

type TokenResponse_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type TokenResponse_AvatarUrl struct {
	AvatarUrl string `protobuf:"bytes,2,opt,name=avatar_url,json=avatarUrl,proto3,oneof"`
}

func (*TokenResponse_Token) isTokenResponse_Response() {}

func (*TokenResponse_AvatarUrl) isTokenResponse_Response() {}

// WebSocketMessage represents the JSON structure for WebSocket communication
type WebSocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebSocketMessage_UserMessage
	//	*WebSocketMessage_AssistantToken
	//	*WebSocketMessage_AvatarUrl
	Payload       isWebSocketMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *WebSocketMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WebSocketMessage) GetPayload() isWebSocketMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebSocketMessage) GetUserMessage() *UserMessage {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_UserMessage); ok {
			return x.UserMessage
		}
	}
	return nil
}

func (x *WebSocketMessage) GetAssistantToken() *AssistantToken {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_AssistantToken); ok {
			return x.AssistantToken
		}
	}
	return nil
}

func (x *WebSocketMessage) GetAvatarUrl() *AvatarUrl {
	if x != nil {
		if x, ok := x.Payload.(*WebSocketMessage_AvatarUrl); ok {
			return x.AvatarUrl
		}
	}
	return nil
}

type isWebSocketMessage_Payload interface {
	isWebSocketMessage_Payload()
}

type WebSocketMessage_UserMessage struct {
	UserMessage *UserMessage `protobuf:"bytes,2,opt,name=user_message,json=userMessage,proto3,oneof"`
}

type WebSocketMessage_AssistantToken struct {
	AssistantToken *AssistantToken `protobuf:"bytes,3,opt,name=assistant_token,json=assistantToken,proto3,oneof"`
}

type WebSocketMessage_AvatarUrl struct {
	AvatarUrl *AvatarUrl `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof"`
}

func (*WebSocketMessage_UserMessage) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_AssistantToken) isWebSocketMessage_Payload() {}

func (*WebSocketMessage_AvatarUrl) isWebSocketMessage_Payload() {}

type UserMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Text           string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserMessage) Reset() {
	*x = UserMessage{}
	mi := &file_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMessage) ProtoMessage() {}

func (x *UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMessage.ProtoReflect.Descriptor instead.
func (*UserMessage) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *UserMessage) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UserMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AssistantToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantToken) Reset() {
	*x = AssistantToken{}
	mi := &file_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantToken) ProtoMessage() {}

func (x *AssistantToken) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantToken.ProtoReflect.Descriptor instead.
func (*AssistantToken) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *AssistantToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AvatarUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarUrl) Reset() {
	*x = AvatarUrl{}
	mi := &file_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarUrl) ProtoMessage() {}

func (x *AvatarUrl) ProtoReflect() protoreflect.Message {
	mi := &file_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarUrl.ProtoReflect.Descriptor instead.
func (*AvatarUrl) Descriptor() ([]byte, []int) {
	return file_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *AvatarUrl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_v1_chat_proto protoreflect.FileDescriptor

const file_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\rv1/chat.proto\x12\vcareerup.v1\"K\n" +
	"\fTokenRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"T\n" +
	"\rTokenResponse\x12\x16\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x12\x1f\n" +
	"\n" +
	"avatar_url\x18\x02 \x01(\tH\x00R\tavatarUrlB\n" +
	"\n" +
	"\bresponse\"\xf1\x01\n" +
	"\x10WebSocketMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12=\n" +
	"\fuser_message\x18\x02 \x01(\v2\x18.careerup.v1.UserMessageH\x00R\vuserMessage\x12F\n" +
	"\x0fassistant_token\x18\x03 \x01(\v2\x1b.careerup.v1.AssistantTokenH\x00R\x0eassistantToken\x127\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\v2\x16.careerup.v1.AvatarUrlH\x00R\tavatarUrlB\t\n" +
	"\apayload\"J\n" +
	"\vUserMessage\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"&\n" +
	"\x0eAssistantToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x1d\n" +
	"\tAvatarUrl\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\\\n" +
	"\x13ConversationService\x12E\n" +
	"\x06Stream\x12\x19.careerup.v1.TokenRequest\x1a\x1a.careerup.v1.TokenResponse\"\x00(\x010\x01B\x92\x01\n" +
	"\x0fcom.careerup.v1B\tChatProtoP\x01Z'github.com/careerup/proto/v1;careerupv1\xa2\x02\x03CXX\xaa\x02\vCareerup.V1\xca\x02\vCareerup\\V1\xe2\x02\x17Careerup\\V1\\GPBMetadata\xea\x02\fCareerup::V1b\x06proto3"

var (
	file_v1_chat_proto_rawDescOnce sync.Once
	file_v1_chat_proto_rawDescData []byte
)

func file_v1_chat_proto_rawDescGZIP() []byte {
	file_v1_chat_proto_rawDescOnce.Do(func() {
		file_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_chat_proto_rawDesc), len(file_v1_chat_proto_rawDesc)))
	})
	return file_v1_chat_proto_rawDescData
}

var file_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_chat_proto_goTypes = []any{
	(*TokenRequest)(nil),     // 0: careerup.v1.TokenRequest
	(*TokenResponse)(nil),    // 1: careerup.v1.TokenResponse
	(*WebSocketMessage)(nil), // 2: careerup.v1.WebSocketMessage
	(*UserMessage)(nil),      // 3: careerup.v1.UserMessage
	(*AssistantToken)(nil),   // 4: careerup.v1.AssistantToken
	(*AvatarUrl)(nil),        // 5: careerup.v1.AvatarUrl
}
var file_v1_chat_proto_depIdxs = []int32{
	3, // 0: careerup.v1.WebSocketMessage.user_message:type_name -> careerup.v1.UserMessage
	4, // 1: careerup.v1.WebSocketMessage.assistant_token:type_name -> careerup.v1.AssistantToken
	5, // 2: careerup.v1.WebSocketMessage.avatar_url:type_name -> careerup.v1.AvatarUrl
	0, // 3: careerup.v1.ConversationService.Stream:input_type -> careerup.v1.TokenRequest
	1, // 4: careerup.v1.ConversationService.Stream:output_type -> careerup.v1.TokenResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_v1_chat_proto_init() }
func file_v1_chat_proto_init() {
	if File_v1_chat_proto != nil {
		return
	}
	file_v1_chat_proto_msgTypes[1].OneofWrappers = []any{
		(*TokenResponse_Token)(nil),
		(*TokenResponse_AvatarUrl)(nil),
	}
	file_v1_chat_proto_msgTypes[2].OneofWrappers = []any{
		(*WebSocketMessage_UserMessage)(nil),
		(*WebSocketMessage_AssistantToken)(nil),
		(*WebSocketMessage_AvatarUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_chat_proto_rawDesc), len(file_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_chat_proto_goTypes,
		DependencyIndexes: file_v1_chat_proto_depIdxs,
		MessageInfos:      file_v1_chat_proto_msgTypes,
	}.Build()
	File_v1_chat_proto = out.File
	file_v1_chat_proto_goTypes = nil
	file_v1_chat_proto_depIdxs = nil
}
